spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:mysql://localhost:22306/handtris
    user: root
    password: 1234
    locations: classpath:/db/migration  # 마이그레이션 파일의 위치
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: HandTris
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mysql://localhost:22306/handtris
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver