spring:
  security:
    oauth2:
      redirect-uri: https://api.checkmatejungle.shop
      client:
        temppassword: ENC(kof7KM9iTyWvb6wVueqmEGZjOyPFRA7+mwS7ioUOOd5fGyahPdVrFA==)
        registration:
          kakao:
            client-name: kakao
            client-id: ENC(uDaiOGmeyUfis1Rn2FvrbummQPeIQ+t2YObAqk+p8GJc4fTjPeIBkoEVkDggqRYo)
            client-secret: ENC(4OAV1P1r3VVnZtS8yEWjVh3ehBOuvzDDEtlW3dzwf7phCbRB/TnRPo1uslNxRr8V)
            client-authentication-method: client_secret_post
            redirect-uri: https://api.checkmatejungle.shop/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
          naver:
            client-name: naver
            client-id: ENC(NND6lQENTv5bBtkfT8kZ7MmT1kJA010W4vKG5k1xmjo=)
            client-secret: ENC(1yN94MaHMO7JJm/zueisA143eQpiXXpx)
            client-authentication-method: client_secret_post
            redirect-uri: https://api.checkmatejungle.shop/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
